version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/tfunfold
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
homebrew_casks:
  - repository:
      owner: winebarrel
      name: homebrew-tfunfold
    homepage: https://github.com/winebarrel/tfunfold
    description: tfunfold expands Terraform for_each / count into individual resources or modules with moved blocks.
    license: MIT
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfunfold"]
          end
